### ISSUE TITLE
-ftrapv reports signed integer overflows on left shift

### ISSUE THREAD

**Issue by nmathewson** [agl/curve25519-donna#31]
Apparently, C thinks that a left shift of a negative number is undefined behavior.  But the donna code does this.

A volunteer contributor to Tor, named "teor", has sent us a patch to fix this issue. We'd like it to go upstream before we merge it, though.  You can see the ticket at https://trac.torproject.org/projects/tor/ticket/13538 .  This code will need a bit of hacking to go into donna.  I'm making this issue as a placeholder.

**Comment by zackw** [comment]
Even if the C committee makes this defined -- and I strongly suspect they won't -- it will be *decades* before C compilers are all updated to acknowledge the change.

The patch should be merged.

**Comment by thestinger** [comment]
@agl: You should at least add `-fwrapv` to CFLAGS to get well-defined wrapping if you depend on it as the Linux kernel does. Clang and GCC really do break code with signed overflow without passing `-fwrapv`.

**Comment by richfelker** [comment]
The right way to "left shift a possibly negative number" is to simply write x*(1<<n). It has the exact semantics you want but without the undefined behavior (assuming no overflow). If you also want well-defined behavior on overflow without depending on non-portable compiler extensions you need to convert to an unsigned type and back.
