### ISSUE TITLE
Check all implementation-defined behavior; possibly workaround

### ISSUE THREAD

**Issue by nmathewson** [agl/curve25519-donna#7]
Right now, both the 32-bit and the 64-bit implementations rely on some implementation-defined behavior.  Specifically, the 32-bit implementation requires:
- Two's complement integers 
- Right-shifting of negative numbers must do sign-extension

And the 64-bit implementation requires:
- Little-endian integers (in fcontract and fexpand)
- Safe unaligned access (in fcontract and fexpand)
- An implementation for uint128_t.

We should at a minimum document these requirements.  One step better is to check for them at compile-time.  One step better than _that_ is to work around them when they fail.

Case by case:
- We've already decided IIRC that supporting non-two's-complement implementations is silly, since they are rare as hen's teeth nowadays. 
- I'm looking around to see if I can find a live 32-bit architecture out there where right-shifting doesn't do sign extension, but so far I've not run into anything.  MSVC and GCC both say that they always do arithmetic shifts.  If we find an architecture we care about, this wouldn't be too hard to fix.
- There are still big-endian architectures around, and architectures where unaligned integer access is disallowed, trap-prone, or allowed to be extra slow.  PPC64 and SPARC64 come to mind.  I think we should just fix the fexpand and fcontract implementations here, since they don't need to be super-fast.
- It would be great if we could make donna-c64's uint128_t work in portable C, but for now that's pretty unlikely.

If you generally agree, I'll keep researching and prepare patches for these.

**Comment by ott** [comment]
I would prefer the implementation to be portable. So I think there has to be a fallback implementation for target architectures which do not support two's complement integers and right shifts with sign-extension. So you don't have to worry about each particular compiler or target architecture but can be confident that the computations are right (but perhaps not as fast as on other architectures).

GCC and MSVC do in fact use two's complement and right shifts with sign-extension on all supported architectures. The macros that are supposed to detect whether a two's complement and right shifts with sign-extensions are supported are broken though: preprocessors expressions are evaluated as `intmax_t` values in the execution environment of the compiler and not in the target execution environment. So if you try to cross-compile for a target architecture that does not support one of the “features” with a compiler on a machine that supports them, the tests will lead to incorrect results. I think it would be better to detect whether they are supported based on the compiler and target architecture.

**Comment by agl** [comment]
Two's complement and arithmetic right-shift can be assumed at this point. No need to worry about anything else. The macros are probably excessive already.

The endianness and alignment issues were fixed by Nick in 8c982df0f9b30391eacc57ac36338a5d43f2de49. Probably time to close this bug after five years :)
